### ISSUE TITLE
getting errors logging into matrix.org account

### ISSUE THREAD

**Issue by hanthor** [farooqkz/chooj#3]
Caught /sync error decryptCriticalEvents@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:65628:14
_callee9$@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:75157:29
tryCatch@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:1522:14
invoke@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:1741:22
["./node_modules/babel-preset-inferno-app/node_modules/regenerator-runtime/runtime.js"]/defineIteratorMethods/</prototype[method]@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:1575:16
asyncGeneratorStep@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:604:16
_next@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:626:9

**Comment by farooqkz** [comment]
Thank you for reporting. I am aware of this problem and am trying to fix it.

**Comment by farooqkz** [comment]
Please test, the problem should have been solved by now.

**Comment by hanthor** [comment]
Unhandled promise rejection TypeError: Object(...)(...) is null
Stack trace:
componentDidUpdate@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/bundle.js:1532:7
["./node_modules/inferno/dist/index.dev.esm.js"]/createDidUpdate/<@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:34081:5
callAll@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:31801:5
applyState@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:34739:5
rerender@app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:34723:7
 
    at ["./node_modules/core-js/internals/host-report-errors.js"]/module.exports (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:9767:49)
    at dispatchEvent (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:18197:121)
    at ["./node_modules/core-js/modules/es.promise.js"]/onUnhandled/</result< (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:18211:16)
    at ["./node_modules/core-js/internals/perform.js"]/module.exports (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:12014:14)
    at ["./node_modules/core-js/modules/es.promise.js"]/onUnhandled/< (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:18208:16)
    at <anonymous> (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:13168:8)
    at run (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:13136:5)
    at listener (app://4f7490a6-1e56-4e11-9081-c0969050cc77/static/js/0.chunk.js:13147:3)

**Comment by farooqkz** [comment]
It should be okay now, only in `development builds` however.

**Comment by farooqkz** [comment]
Closing due to inactivity
